int bitAnd(int, int);
int test_bitAnd(int, int);
int upperBits(int);
int test_upperBits(int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int isGreater(int, int);
int test_isGreater(int, int);
int bitCount(int);
int test_bitCount(int);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
